# Site settings
title: Brian Zelip
email: bzelip@gmail.com
description: "Brian Zelip is interested in [presenting, curating, understanding] data."
baseurl: ""
url: "http://brianzelip.github.io/personal"

# Build settings
markdown: kramdown
permalink: pretty